### ISSUE TITLE
De zinnen lopen niet lekker.

### ISSUE THREAD

**Issue by edwardbrosens** [MicrosoftDocs/architecture-center.nl-nl#2]
Dit artikel is laks vertaald of onzorgvuldig geschreven.
This article contains errors with translation or is just badly written.
---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f259ccea-882e-9496-27cf-af8d13edaae4
* Version Independent ID: a7bab5c8-7227-e836-a721-0c54f94a2d8c
* Content: [Communicatie in microservices](https://docs.microsoft.com/nl-nl/azure/architecture/microservices/design/interservice-communication#feedback)
* Content Source: [docs/microservices/design/interservice-communication.md](https://github.com/microsoftdocs/architecture-center.nl-nl/blob/live/docs/microservices/design/interservice-communication.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
Hallo, @edwardbrosens 

Vielen Dank für Ihr Feedback. Die betroffene Seite wurde maschinenübersetzt. Daher kann es sein, dass der Inhalt nicht immer verständlich ist. Wir haben vor Kurzem die Option „Read in English“ (Auf Englisch lesen) rechts hinzugefügt, sodass Sie zur englischen Version wechseln können, ohne die Spracheinstellungen ändern zu müssen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
